version: '3'
services:
  server:
    build: .
    image: server:v0
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    volumes:
      - ./mongo_data:/data/db
    expose: 
      - 27017
    ports:
      - 27017:27017
